// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParmeniaHub.Infrastructure.Persistence;

#nullable disable

namespace ParmeniaHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260831004353_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParmeniaHub.Domain.Convocatorias.Convocatoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTimeOffset?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTimeOffset>("FinInscripciones")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin_inscripciones");

                    b.Property<DateTimeOffset>("FinPrograma")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin_programa");

                    b.Property<DateTimeOffset>("InicioInscripciones")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio_inscripciones");

                    b.Property<DateTimeOffset>("InicioPrograma")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio_programa");

                    b.Property<string>("Requisitos")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("requisitos");

                    b.Property<string>("TipoPrograma")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_programa");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("TipoPrograma", "Estado");

                    b.ToTable("convocatorias", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
